### ISSUE TITLE
Gets stuck if file lock fails

### ISSUE THREAD

**Issue by jan-rosendahl-rwth** [kanedo/checkout_code#2]
If for some reason a file lock can't be achieved (in my case a faulty nfs mount) the program gets stuck at

https://github.com/kanedo/checkout_code/blob/4545a32ea7cf424e98bff04a15186dcf240fb4d1/bin/checkout_code#L94-L95

failing after a time-out period would be nicer behaviour .

**Comment by kanedo** [comment]
I added a timeout option in branch `dev/timeout`. Would you mind testing this? 
I have no good way of simulating a timeout. If it works for you I will it merge to the master

**Comment by jan-rosendahl-rwth** [comment]
Yes, that works. I got

> [ERROR:checkout_code] Could not acquire lock. Timeout.

Thanks for the incredibly fast response!
